//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace next.web.core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("next.web.core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;meta charset=&quot;utf-8&quot;&gt;
        ///&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, shrink-to-fit=no&quot;&gt;
        ///&lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///&lt;meta name=&quot;author&quot; content=&quot;&quot;&gt;
        ///&lt;title&gt;oxford.leads.web: &lt;/title&gt;		
        ///&lt;!-- googleapis : fonts --&gt;
        ///&lt;link href=&quot;https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&amp;amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///		
        ///&lt;!-- popper --&gt;
        ///&lt;script src=&quot;https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js&quot;&gt;&lt;/script&gt;
        ///		
        ///&lt;!-- bootstrap --&gt;
        ///&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string base_account_heading {
            get {
                return ResourceManager.GetString("base_account_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///		
        ///&lt;!-- Reauthorize Modal --&gt;  		 		 		 		 		 		 		 		 		 		 		 		 		 		 		
        ///&lt;!-- Reauthorize: trigger modal --&gt;
        ///&lt;button id=&quot;btn-account-authorize-show&quot; type=&quot;button&quot; class=&quot;btn btn-primary d-none&quot; data-bs-toggle=&quot;modal&quot; data-bs-target=&quot;#account-authorize-modal&quot;&gt;
        ///	Launch static backdrop modal
        ///&lt;/button&gt;
        ///		
        ///&lt;!-- Reauthorize: Modal Content --&gt;
        ///&lt;div class=&quot;modal fade&quot; id=&quot;account-authorize-modal&quot; data-bs-backdrop=&quot;static&quot; data-bs-keyboard=&quot;false&quot; tabindex=&quot;-1&quot; aria-labelledby=&quot;account-authorize-label&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string base_account_modals {
            get {
                return ResourceManager.GetString("base_account_modals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;cover-container d-flex h-100 p-3 mx-auto flex-column&quot;&gt;
        ///	&lt;header class=&quot;masthead mb-auto&quot; style=&quot;border-bottom: #444 solid 1px; padding-bottom: 2px&quot;&gt;
        ///		&lt;div class=&quot;inner&quot;&gt;
        ///			&lt;h3 class=&quot;masthead-brand&quot;&gt;
        ///				&lt;i class=&quot;bi bi-bank2&quot;/&gt;
        ///				&lt;span&gt;Oxford Legal Lead UI&lt;/span&gt;
        ///			&lt;/h3&gt;
        ///			&lt;nav id=&quot;masthead-nav-menu&quot; class=&quot;nav nav-masthead justify-content-center&quot;&gt;
        ///				&lt;a name=&quot;subcontent-home&quot; class=&quot;nav-link active&quot; href=&quot;javascript:setDisplay(&apos;home&apos;)&quot;&gt;Home&lt;/a&gt;
        ///				&lt;a name=&quot;subcontent-profile&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string base_account_shell {
            get {
                return ResourceManager.GetString("base_account_shell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;app-side-menu&quot; name=&quot;left-menu&quot;&gt;
        ///		&lt;div data-position-index=&quot;0&quot; name=&quot;left-menu-icon&quot; class=&quot;row&quot;&gt;
        ///			&lt;a class=&quot;text-primary&quot; href=&quot;/&quot;&gt;
        ///				&lt;i class=&quot;bi bi-three-dots&quot;&gt;&lt;/i&gt;
        ///			&lt;/a&gt;
        ///		&lt;/div&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string base_logout_menu {
            get {
                return ResourceManager.GetString("base_logout_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;menu-container&quot; name=&quot;menu-container&quot;&gt;
        ///	&lt;div id=&quot;app-side-menu-border&quot; name=&quot;left-menu-border&quot;&gt;&lt;/div&gt;
        ///	&lt;div id=&quot;app-side-menu&quot; name=&quot;left-menu&quot;&gt;
        ///		&lt;div data-position-index=&quot;0&quot; name=&quot;left-menu-icon&quot; class=&quot;row&quot;&gt;
        ///			&lt;a class=&quot;text-primary&quot; href=&quot;/&quot;&gt;
        ///				&lt;i class=&quot;bi bi-three-dots&quot;&gt;&lt;/i&gt;
        ///			&lt;/a&gt;
        ///		&lt;/div&gt;
        ///		&lt;div data-position-index=&quot;1&quot; name=&quot;left-menu-home&quot; class=&quot;row&quot;&gt;
        ///			&lt;a class=&quot;text-primary&quot; href=&quot;/home&quot;&gt;
        ///				&lt;i class=&quot;bi bi-house&quot; title=&quot;Home&quot;&gt;&lt;/i&gt;
        ///			&lt;/a&gt;
        ///		&lt;/div&gt;
        ///		&lt;div id=&quot;my-accou [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string base_menu {
            get {
                return ResourceManager.GetString("base_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Permissions_API&quot;: &quot;http://api.legallead.co/&quot;,
        ///  &quot;api.permissions&quot;: {
        ///    &quot;destination&quot;: &quot;remote&quot;,
        ///    &quot;remote&quot;: &quot;http://api.legallead.co/&quot;,
        ///    &quot;local&quot;: &quot;https://localhost:44345/&quot;
        ///  },
        ///  &quot;stripe.payment&quot;: {
        ///    &quot;key&quot;: &quot;test&quot;,
        ///    &quot;names&quot;: {
        ///      &quot;test&quot;: &quot;sk_test_51LCZucDhgP60CL9xtS9RSEC5IhGsKkZwnNxwFwpHbDHLLBLvB87uICAJB5fVZNyqEHNpI9ZbLYwFFKXPNnbgucs200OOT3UvbK&quot;,
        ///      &quot;prod&quot;: &quot;sk_test_51LCZucDhgP60CL9xtS9RSEC5IhGsKkZwnNxwFwpHbDHLLBLvB87uICAJB5fVZNyqEHNpI9ZbLYwFFKXPNnbgucs200OOT3UvbK&quot;
        ///    } [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string core_configuration {
            get {
                return ResourceManager.GetString("core_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;main role=&quot;main&quot; class=&quot;inner cover&quot;&gt;
        ///	&lt;div id=&quot;download-card&quot; class=&quot;card&quot;&gt;
        ///		&lt;div class=&quot;card-body text-start&quot;&gt;
        ///			&lt;h5 id=&quot;download-title&quot; class=&quot;card-title text-start&quot;&gt;Download&lt;/h5&gt;
        ///			&lt;div id=&quot;download-card-content&quot;&gt;
        ///				&lt;div class=&quot;row&quot;&gt;
        ///					&lt;div class=&quot;text-start&quot;&gt;
        ///						&lt;span class=&quot;text-primary data-label&quot;&gt;External Id:&lt;/span&gt;
        ///						&lt;span id=&quot;spn-download-external-id&quot; name=&quot;download-external-id&quot; class=&quot;data-value&quot;&gt; - &lt;/span&gt;
        ///					&lt;/div&gt;
        ///				&lt;/div&gt;
        ///				&lt;div class=&quot;row&quot;&gt;
        ///					&lt;div class=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string download_file_template {
            get {
                return ResourceManager.GetString("download_file_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///        &lt;meta charset=&quot;utf-8&quot;&gt;
        ///        &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, shrink-to-fit=no&quot;&gt;
        ///        &lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///        &lt;meta name=&quot;author&quot; content=&quot;&quot;&gt;
        ///        &lt;title&gt;Home - Oxford Legal Leads&lt;/title&gt;
        ///        &lt;!-- Favicon--&gt;
        ///        &lt;link rel=&quot;icon&quot; type=&quot;image/x-icon&quot; href=&quot;assets/favicon.ico&quot;&gt;
        ///        &lt;!-- Bootstrap icons--&gt;
        ///        &lt;link href=&quot;https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icon [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string index_page {
            get {
                return ResourceManager.GetString("index_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;main role=&quot;main&quot; class=&quot;inner cover&quot;&gt;
        ///	&lt;div id=&quot;invoice-card&quot; class=&quot;card&quot;&gt;
        ///		&lt;div class=&quot;card-body text-start&quot;&gt;
        ///			&lt;h5 id=&quot;invoice-fallback-title&quot; class=&quot;card-title text-start&quot;&gt;Invoice&lt;/h5&gt;
        ///			&lt;div id=&quot;invoice-card-content&quot;&gt;&lt;/div&gt;
        ///		&lt;/div&gt;
        ///	&lt;/div&gt;
        ///&lt;/main&gt;.
        /// </summary>
        internal static string invoice_page {
            get {
                return ResourceManager.GetString("invoice_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;main role=&quot;main&quot; class=&quot;inner cover&quot;&gt;
        ///	&lt;div class=&quot;card&quot;&gt;
        ///		&lt;div class=&quot;card-body&quot;&gt;
        ///			&lt;h5 class=&quot;card-title&quot;&gt;Logout&lt;/h5&gt;
        ///			&lt;p&gt;You have been successfully logged out of application.&lt;/p&gt;
        ///		&lt;/div&gt;
        ///	&lt;/div&gt;
        ///&lt;/main&gt;.
        /// </summary>
        internal static string logout_page {
            get {
                return ResourceManager.GetString("logout_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;main role=&quot;main&quot; class=&quot;inner cover&quot;&gt;
        ///	&lt;div id=&quot;payment-card-content&quot;&gt;
        ///		
        ///	&lt;/div&gt;
        ///&lt;/main&gt;.
        /// </summary>
        internal static string payment_confirmation_page {
            get {
                return ResourceManager.GetString("payment_confirmation_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;tr id=&quot;tr-user-interaction-purchased&quot; class=&quot;d-none&quot; name=&quot;user-interaction&quot; data-context=&quot;purchased&quot;&gt;
        ///	&lt;td style=&quot;padding: 20px&quot; colspan=&quot;2&quot;&gt;
        ///		&lt;hr size=&quot;1&quot; noshade=&quot;&quot;&gt;
        ///		&lt;p&gt;
        ///			Your request has been purchased successfully.
        ///		&lt;/p&gt;
        ///		&lt;br&gt;
        ///		&lt;p&gt;
        ///			Click below to download this search.
        ///		&lt;/p&gt;
        ///		&lt;div class=&quot;d-flex justify-content-between&quot;&gt;
        ///			&lt;center style=&quot;width: 100%&quot;&gt;
        ///				&lt;button id=&quot;btn-user-interaction-download&quot; name=&quot;bttn-download&quot; class=&quot;btn btn-primary w-75 m-2&quot; onclick=&quot;javascript:histo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string search_download_template {
            get {
                return ResourceManager.GetString("search_download_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;table automationId=&quot;search-history-table&quot; name=&quot;search-dt-table&quot;&gt;
        ///	&lt;colgroup&gt;
        ///		&lt;col name=&quot;requested-date&quot; /&gt;
        ///		&lt;col name=&quot;state-abbr&quot; style=&quot;width: 60px&quot; /&gt;
        ///		&lt;col name=&quot;county-name&quot; style=&quot;width: 150px&quot; /&gt;
        ///		&lt;col name=&quot;begin-date&quot; style=&quot;width: 95px&quot; /&gt;
        ///		&lt;col name=&quot;ending-date&quot; style=&quot;width: 95px&quot; /&gt;
        ///		&lt;col name=&quot;search-status&quot; style=&quot;width: 90px&quot; /&gt;
        ///	&lt;/colgroup&gt;
        ///	&lt;thead&gt;
        ///		&lt;tr&gt;
        ///			&lt;th style=&quot;padding-left: 3px;&quot;&gt;Request Date&lt;/th&gt;
        ///			&lt;th style=&quot;padding-left: 3px;&quot;&gt;State&lt;/th&gt;
        ///			&lt;th style=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string search_table_layout {
            get {
                return ResourceManager.GetString("search_table_layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;sidemnu-div-user-status&quot;&gt;
        ///&lt;table id=&quot;sidemnu-table-user-status&quot;  class=&quot;table table-sm table-bordered&quot; automationid=&quot;user-status-table&quot; name=&quot;user-status-table&quot;&gt;
        ///	&lt;colgroup&gt;
        ///		&lt;col name=&quot;current-dt&quot; style=&quot;width: 100px&quot; /&gt;
        ///		&lt;col name=&quot;user-level&quot; style=&quot;width: 85px&quot; /&gt;
        ///		&lt;col name=&quot;user-name&quot; /&gt;
        ///		&lt;col name=&quot;user-status&quot; style=&quot;width: 60px&quot; /&gt;
        ///		&lt;col name=&quot;payment-status&quot; style=&quot;width: 24px&quot; /&gt;
        ///	&lt;/colgroup&gt;
        ///	&lt;tbody&gt;
        ///		&lt;tr id=&quot;tr-status-information&quot;&gt;
        ///			&lt;td class=&quot;text-start&quot;&gt;&lt;span id=&quot;s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string status_menu {
            get {
                return ResourceManager.GetString("status_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, shrink-to-fit=no&quot;&gt;
        ///		&lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///		&lt;meta name=&quot;author&quot; content=&quot;&quot;&gt;
        ///		&lt;title&gt;oxford.leads.web: cache manager&lt;/title&gt;
        ///		&lt;!-- googleapis : fonts --&gt;
        ///		&lt;link href=&quot;https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&amp;amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///		
        ///		&lt;!-- popper --&gt;
        ///		&lt;script src=&quot;https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/pop [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string user_cache {
            get {
                return ResourceManager.GetString("user_cache", resourceCulture);
            }
        }
    }
}
