//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace next.core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("next.core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Initial_View&quot;: &quot;introduction&quot;,
        ///  &quot;Permissions_API&quot;: &quot;http://api.legallead.co/&quot;,
        ///  &quot;api.permissions&quot;: {
        ///    &quot;destination&quot;: &quot;remote&quot;,
        ///    &quot;remote&quot;: &quot;http://api.legallead.co/&quot;,
        ///    &quot;local&quot;: &quot;https://localhost:44345/&quot;
        ///  },
        ///  &quot;landings&quot;: {
        ///    &quot;search&quot;: &quot;mysearch&quot;
        ///  },
        ///  &quot;user&quot;: {
        ///    &quot;session_timeout&quot;: 20
        ///  }
        ///  &quot;stripe&quot;:{
        ///    &quot;key&quot;: &quot;sk_test_51LCZucDhgP60CL9xtS9RSEC5IhGsKkZwnNxwFwpHbDHLLBLvB87uICAJB5fVZNyqEHNpI9ZbLYwFFKXPNnbgucs200OOT3UvbK&quot;
        ///  },
        ///  &quot;queue&quot;: {
        ///    &quot;name&quot;: &quot;legallead.reader. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string appsettings {
            get {
                return ResourceManager.GetString("appsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;debug.user&quot;: {
        ///    &quot;name&quot;: &quot;test.account&quot;,
        ///    &quot;code&quot;: &quot;1234-AbcD4321&quot;
        ///  },
        ///  &quot;debug.login&quot;: {
        ///    &quot;passthru&quot;: false
        ///  },
        ///  &quot;user&quot;: {
        ///    &quot;session_timeout&quot;: 60
        ///  }
        ///}.
        /// </summary>
        internal static string appsettings_debug {
            get {
                return ResourceManager.GetString("appsettings-debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////*
        ///* Forms
        ///*/
        ///.form-control:focus {
        ///	background-color: #444;
        ///	color: rgb(240, 240, 240)
        ///}
        ///
        ///.form-control {
        ///    background-color: transparent;
        ///    border-color: #555;
        ///    color: ghostwhite;
        ///}
        ///
        ///.form-control.error {
        ///    border-color: red;
        ///}
        ///label.error {
        ///    color: red;
        ///    font-size: small;
        ///}
        ///div.help-text {
        ///    font-size: small;
        ///}
        ///
        ////*
        /// * Header
        /// */
        ///div[name=&quot;header&quot;] {
        ///    height: 50px; 
        ///    border-bottom: #444 solid 1px;
        ///    margin-top: 5px;
        ///}
        ///
        ///
        ////*
        /// * Loader
        /// */
        ///div[ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string base_css {
            get {
                return ResourceManager.GetString("base-css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;script type=&quot;text/javascript&quot;&gt;
        ///			CefSharp.BindObjectAsync(&quot;jsHandler&quot;, &quot;jsHandler&quot;);
        ///		&lt;/script&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, shrink-to-fit=no&quot;&gt;
        ///		&lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///		&lt;meta name=&quot;author&quot; content=&quot;&quot;&gt;
        ///		&lt;title&gt;legallead.ui&lt;/title&gt;
        ///		&lt;!-- googleapis : fonts --&gt;
        ///		&lt;link href=&quot;https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&amp;display=swap&quot; rel=&quot;stylesheet&quot; /&gt;
        ///		&lt;!-- bootstrap --&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string blank_html {
            get {
                return ResourceManager.GetString("blank-html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @charset &quot;UTF-8&quot;;/*!
        /// * Bootstrap  v5.3.2 (https://getbootstrap.com/)
        /// * Copyright 2011-2023 The Bootstrap Authors
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/main/LICENSE)
        /// */:root,[data-bs-theme=light]{--bs-blue:#0d6efd;--bs-indigo:#6610f2;--bs-purple:#6f42c1;--bs-pink:#d63384;--bs-red:#dc3545;--bs-orange:#fd7e14;--bs-yellow:#ffc107;--bs-green:#198754;--bs-teal:#20c997;--bs-cyan:#0dcaf0;--bs-black:#000;--bs-white:#fff;--bs-gray:#6c757d;--bs-gray-dark:#343a40;--bs-gray-100:#f8f9fa;--b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bootstrapmin_css {
            get {
                return ResourceManager.GetString("bootstrapmin-css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- Reauthorize Modal --&gt;
        ///&lt;!-- Reauthorize: trigger modal --&gt;
        ///&lt;button id=&quot;btn-account-authorize-show&quot; type=&quot;button&quot; class=&quot;btn btn-primary d-none&quot; data-bs-toggle=&quot;modal&quot; data-bs-target=&quot;#account-authorize-modal&quot;&gt;
        ///  Launch static backdrop modal
        ///&lt;/button&gt;
        ///
        ///&lt;!-- Reauthorize: Modal Content --&gt;
        ///&lt;div class=&quot;modal fade&quot; id=&quot;account-authorize-modal&quot; data-bs-backdrop=&quot;static&quot;
        ///        data-bs-keyboard=&quot;false&quot; tabindex=&quot;-1&quot; 
        ///        aria-labelledby=&quot;account-authorize-label&quot; aria-hidden=&quot;true&quot;&gt;
        ///  &lt;div class= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string common_authenticate {
            get {
                return ResourceManager.GetString("common-authenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script name=&quot;re-authenticate-js&quot;&gt;
        ///
        ///if (typeof isValidEmail != &apos;function&apos;) {
        ///	window.isValidEmail = function(email){
        ///	const res = /^(([^&lt;&gt;()\[\]\\.,;:\s@&quot;]+(\.[^&lt;&gt;()\[\]\\.,;:\s@&quot;]+)*)|(&quot;.+&quot;))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
        ///	return res.test(email.toLowerCase());};
        ///}
        ///let authformvalidators = [
        ///	{
        ///		&quot;name&quot;: &quot;isEmailOrUser&quot;,
        ///		&quot;action&quot;: function (value, element, params) {
        ///			if (!value) { return false; }
        ///			if (value == null) { return fal [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string common_authenticate_js {
            get {
                return ResourceManager.GetString("common-authenticate-js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- Reauthorize Modal --&gt;
        ///&lt;!-- Reauthorize: trigger modal --&gt;
        ///&lt;button id=&quot;btn-account-authorize-show&quot; type=&quot;button&quot; class=&quot;btn btn-primary d-none&quot; data-bs-toggle=&quot;modal&quot; data-bs-target=&quot;#account-authorize-modal&quot;&gt;
        ///  Launch static backdrop modal
        ///&lt;/button&gt;
        ///
        ///&lt;!-- Reauthorize: Modal Content --&gt;
        ///&lt;div class=&quot;modal fade&quot; id=&quot;account-authorize-modal&quot; data-bs-backdrop=&quot;static&quot;
        ///        data-bs-keyboard=&quot;false&quot; tabindex=&quot;-1&quot; 
        ///        aria-labelledby=&quot;account-authorize-label&quot; aria-hidden=&quot;true&quot;&gt;
        ///  &lt;div class= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string common_dialogue {
            get {
                return ResourceManager.GetString("common-dialogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///			&lt;h3 class=&quot;masthead-brand&quot;&gt;
        ///				&lt;i class=&quot;bi bi-bank2&quot;&gt;&lt;/i&gt;
        ///				&lt;span&gt;Legal Lead UI&lt;/span&gt;
        ///			&lt;/h3&gt;.
        /// </summary>
        internal static string common_mast_head_html {
            get {
                return ResourceManager.GetString("common-mast-head-html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{
        ///		&quot;id&quot;: 1,
        ///		&quot;name&quot;: &quot;Loading&quot;,
        ///		&quot;message&quot;: &quot;Reading application configuration&quot;,
        ///		&quot;color&quot;: &quot;Gray&quot;
        ///	},
        ///	{
        ///		&quot;id&quot;: 10,
        ///		&quot;name&quot;: &quot;Ready&quot;,
        ///		&quot;message&quot;: &quot;&quot;,
        ///		&quot;color&quot;: &quot;ForestGreen&quot;
        ///	},
        ///	{
        ///		&quot;id&quot;: 20,
        ///		&quot;name&quot;: &quot;Error&quot;,
        ///		&quot;message&quot;: &quot;An error occurred during application processing.&quot;,
        ///		&quot;color&quot;: &quot;Red&quot;
        ///	},
        ///	{
        ///		&quot;id&quot;: 30,
        ///		&quot;name&quot;: &quot;Submitting&quot;,
        ///		&quot;message&quot;: &quot;Sending form data to api server.&quot;,
        ///		&quot;color&quot;: &quot;Mango&quot;
        ///	},
        ///	{
        ///		&quot;id&quot;: 40,
        ///		&quot;name&quot;: &quot;Failed&quot;,
        ///		&quot;message&quot;: &quot;Data transmissi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string common_status {
            get {
                return ResourceManager.GetString("common-status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	&lt;script type=&quot;text/javascript&quot;&gt;
        ///		try {
        ///			CefSharp.BindObjectAsync(&quot;jsHandler&quot;, &quot;jsHandler&quot;);
        ///		} catch {}		
        ///	&lt;/script&gt;.
        /// </summary>
        internal static string commoncefhandler_html {
            get {
                return ResourceManager.GetString("commoncefhandler-html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;
        ///	
        ///	let clientScriptActivated = false;
        ///
        ///	function commonClientScript() {
        ///		try {
        ///			/* user injected block */
        ///		} catch(err) {
        ///			console.debug(err);
        ///		}
        ///	}
        ///	if (clientScriptActivated) {
        ///		setTimeout( () =&gt; { commonClientScript(); }, 250);
        ///	}
        ///&lt;/script&gt;.
        /// </summary>
        internal static string commonclientinjection_js {
            get {
                return ResourceManager.GetString("commonclientinjection-js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///if (typeof isValidEmail != &apos;function&apos;) {
        ///	window.isValidEmail = function(email){
        ///	const res = /^(([^&lt;&gt;()\[\]\\.,;:\s@&quot;]+(\.[^&lt;&gt;()\[\]\\.,;:\s@&quot;]+)*)|(&quot;.+&quot;))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
        ///	return res.test(email.toLowerCase());};
        ///}
        ///let customvalidators = [
        ///	{
        ///		&quot;name&quot;: &quot;isEmailOrUser&quot;,
        ///		&quot;action&quot;: function (value, element, params) {
        ///			if (!value) { return false; }
        ///			if (value == null) { return false; }
        ///			if (value.length == 0) { ret [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string commondialogscript_js {
            get {
                return ResourceManager.GetString("commondialogscript-js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///      &lt;footer class=&quot;mastfoot mt-auto&quot;&gt;
        ///			&lt;div id=&quot;footer-copy&quot; class=&quot;float-end&quot;&gt;
        ///				&lt;span id=&quot;footer-copy-span&quot;&gt;{0}&lt;/span&gt;
        ///			&lt;/div&gt;
        ///			&lt;div id=&quot;footer-reload&quot; class=&quot;float-start&quot; style=&quot;display:none&quot;&gt;
        ///				&lt;a id=&quot;footer-reload-link&quot; href=&quot;javascript:reloadContent()&quot; class=&quot;text-secondary text-decoration-none&quot;&gt;Reload&lt;/a&gt;
        ///			&lt;/div&gt;
        ///      &lt;/footer&gt;.
        /// </summary>
        internal static string commonfooter_html {
            get {
                return ResourceManager.GetString("commonfooter-html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///		&lt;!-- googleapis : fonts --&gt;
        ///		&lt;link href=&quot;https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&amp;display=swap&quot; rel=&quot;stylesheet&quot; /&gt;
        ///		
        ///		&lt;!-- popper --&gt;
        ///		&lt;script src=&quot;https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js&quot;&gt;&lt;/script&gt;
        ///
        ///		&lt;!-- bootstrap --&gt;
        ///		&lt;script src=&quot;https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js&quot;&gt;&lt;/script&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; href=&quot;https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css&quot;&gt;
        ///		&lt;link re [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string commonheadings_html {
            get {
                return ResourceManager.GetString("commonheadings-html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///		
        ///	function getPageName() {
        ///		const defaultName = &quot;home&quot;;
        ///		const colon = &quot;:&quot;;
        ///		var current_title = $(document).attr(&apos;title&apos;);
        ///		if ( undefined === current_title || null === current_title || current_title.length === 0) return defaultName;
        ///		if (current_title.indexOf(colon) &lt; 0 || current_title.split(colon).length &lt; 2) return defaultName;
        ///		var landing = current_title.split(&apos;:&apos;)[1].trim();
        ///		return landing == &quot;account&quot; ? &quot;myaccount-~0&quot; : &quot;home-~0&quot;;
        ///	}
        ///		
        ///	function getDisplay( ) {
        ///			const fin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string commonreload_js {
            get {
                return ResourceManager.GetString("commonreload-js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IsVisible&quot;: false,
        ///    &quot;Items&quot;: [
        ///      {
        ///        &quot;Name&quot;: &quot;Home&quot;,
        ///        &quot;IsDisplayed&quot;: true,
        ///        &quot;IsSelected&quot;: true
        ///      },
        ///      {
        ///        &quot;Name&quot;: &quot;Error&quot;,
        ///        &quot;IsDisplayed&quot;: true,
        ///        &quot;IsSelected&quot;: false
        ///      },
        ///      {
        ///        &quot;Name&quot;: &quot;MyAccount&quot;,
        ///        &quot;IsDisplayed&quot;: false,
        ///        &quot;IsSelected&quot;: false
        ///      }
        ///    ]
        ///  }.
        /// </summary>
        internal static string contextmenu {
            get {
                return ResourceManager.GetString("contextmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;head&gt;
        ///		&lt;!-- script: common-cef-handler --&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, shrink-to-fit=no&quot;&gt;
        ///		&lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///		&lt;meta name=&quot;author&quot; content=&quot;&quot;&gt;
        ///		&lt;title&gt;legallead.ui: error&lt;/title&gt;
        ///		&lt;!-- block: common-headings --&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; name=&quot;cover-css&quot; href=&quot;https://getbootstrap.com/docs/4.0/examples/cover/cover.css&quot; /&gt;
        ///		&lt;!-- common styles --&gt;	
        ///		&lt;link rel=&quot;stylesheet&quot; name=&quot;base&quot; href=&quot;css/base.css&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string error_html {
            get {
                return ResourceManager.GetString("error-html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style name=&quot;css/error.css&quot;&gt;
        ///
        ///#errorbox {
        ///    position: relative;
        ///    height: 40vh
        ///}
        ///
        ///#errorbox .errorbox {
        ///    position: absolute;
        ///    left: 50%;
        ///    top: 50%;
        ///    -webkit-transform: translate(-50%,-50%);
        ///    -ms-transform: translate(-50%,-50%);
        ///    transform: translate(-50%,-50%)
        ///}
        ///
        ///.errorbox {
        ///    max-width: 560px;
        ///    width: 100%;
        ///    padding-left: 160px;
        ///    line-height: 1.1
        ///}
        ///
        ///.errorbox .errorbox-callout {
        ///    position: absolute;
        ///    left: 0;
        ///    top: 0;
        ///    display: inline- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string errorbox_css {
            get {
                return ResourceManager.GetString("errorbox-css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{
        ///		&quot;id&quot;: &quot;500&quot;,
        ///		&quot;isDefault&quot; : true,
        ///		&quot;code&quot;: &quot;Unexpected Error&quot;,
        ///		&quot;description&quot;: [
        ///			&quot;Application encountered an unexpected error. &quot;,
        ///			&quot;Please contact system administrator for additional details or information regarding this error.&quot;
        ///		]
        ///	}, 
        ///	{
        ///		&quot;id&quot;: &quot;503&quot;,
        ///		&quot;code&quot;: &quot;Internet Unavailable&quot;,
        ///		&quot;description&quot;: [
        ///			&quot;Application is unable to connect to internet. &quot;,
        ///			&quot;Please check your internet settings, router, and/or firewall settings &quot;,
        ///			&quot;to resolve this issue.&quot;
        ///		]
        ///	}, 
        ///	{ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string errorstatus_json {
            get {
                return ResourceManager.GetString("errorstatus-json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///	&lt;head&gt;
        ///		&lt;!-- script: common-cef-handler --&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, shrink-to-fit=no&quot;&gt;
        ///		&lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///		&lt;meta name=&quot;author&quot; content=&quot;&quot;&gt;
        ///		&lt;title&gt;legallead.ui: home&lt;/title&gt;
        ///		&lt;!-- block: common-headings --&gt;
        ///		&lt;!-- common styles --&gt;	
        ///		&lt;link rel=&quot;stylesheet&quot; name=&quot;base&quot; href=&quot;css/base.css&quot; /&gt;
        ///		&lt;style name=&quot;subcontent-css&quot;&gt;
        ///
        ///			div.subcontent {
        ///				width: 50%; 
        ///				min-width: 400px;
        ///				ma [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string home_html {
            get {
                return ResourceManager.GetString("home-html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;card&quot;&gt;
        ///    &lt;div class=&quot;card-body&quot;&gt;
        ///        &lt;h5 class=&quot;card-title&quot;&gt;Login&lt;/h5&gt;
        ///        &lt;form id=&quot;form-login&quot; name=&quot;form-login&quot;&gt;
        ///            &lt;div class=&quot;mb-3&quot;&gt;
        ///                &lt;label for=&quot;username&quot; class=&quot;form-label&quot;&gt;User Name / Email:&lt;/label&gt;
        ///                &lt;input type=&quot;text&quot; class=&quot;form-control&quot; id=&quot;username&quot; name=&quot;username&quot; aria-describedby=&quot;username-help&quot;&gt;
        ///                &lt;div id=&quot;username-help&quot; class=&quot;text-secondary help-text&quot;&gt;
        ///                    Provide user-name or email address.
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string homelogin_html {
            get {
                return ResourceManager.GetString("homelogin-html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;card&quot;&gt;
        ///    &lt;div class=&quot;card-body&quot;&gt;
        ///        &lt;h5 class=&quot;card-title&quot;&gt;Register&lt;/h5&gt;
        ///        &lt;form id=&quot;form-register&quot; name=&quot;form-register&quot;&gt;
        ///            &lt;div class=&quot;mb-3&quot;&gt;
        ///                &lt;label for=&quot;register-username&quot; class=&quot;form-label&quot;&gt;User Name:&lt;/label&gt;
        ///                &lt;input  type=&quot;text&quot; class=&quot;form-control&quot; 
        ///                        id=&quot;register-username&quot; name=&quot;username&quot; 
        ///                        maxlength=&quot;255&quot; minlength=&quot;8&quot;
        ///                        aria-describedby=&quot;register-username-help [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string homeregister_html {
            get {
                return ResourceManager.GetString("homeregister-html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///let formNames = [ &quot;form-login&quot;, &quot;form-register&quot; ];
        ///let buttonNames = [ &quot;form-login-submit&quot;, &quot;form-register-submit&quot; ];
        ///var contacticons = {
        ///    spin: &quot;i[name=&apos;message-send-spinner&apos;]&quot;,
        ///    normal: &quot;i[name=&apos;message-send&apos;]&quot;
        ///}
        ///
        ///function isValidEmail( email ) {
        ///	const res = /^(([^&lt;&gt;()\[\]\\.,;:\s@&quot;]+(\.[^&lt;&gt;()\[\]\\.,;:\s@&quot;]+)*)|(&quot;.+&quot;))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
        ///	return res.test(email.toLowerCase());
        ///}
        ///function initializeValidator() {
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string homevalidation_js {
            get {
                return ResourceManager.GetString("homevalidation-js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///                &lt;br/&gt;
        ///                &lt;p&gt;
        ///					Legal Lead is an application used to locate public data from county courts.
        ///				&lt;/p&gt;
        ///				&lt;p&gt;
        ///					From this application you can retrieve: &lt;br /&gt;
        ///				&lt;/p&gt;
        ///				&lt;div name=&quot;subcontent-home-bullet-list&quot; class=&quot;text-left&quot;&gt;
        ///					&lt;ol&gt;
        ///						&lt;li&gt;Case Details&lt;/li&gt;
        ///						&lt;li&gt;Defendant Information&lt;/li&gt;
        ///						&lt;li&gt;Court Information&lt;/li&gt;
        ///					&lt;/ol&gt;
        ///				&lt;/div&gt;
        ///                &lt;div name=&quot;page-call-to-action&quot;&gt;
        ///					&lt;p&gt;
        ///						&lt;a href=&quot;javascript:setDisplay(&apos;lo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string homewelcome_html {
            get {
                return ResourceManager.GetString("homewelcome-html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;script type=&quot;text/javascript&quot;&gt;
        ///			CefSharp.BindObjectAsync(&quot;jsHandler&quot;, &quot;jsHandler&quot;);
        ///		&lt;/script&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, shrink-to-fit=no&quot;&gt;
        ///		&lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///		&lt;meta name=&quot;author&quot; content=&quot;&quot;&gt;
        ///		&lt;title&gt;legallead.ui: introduction&lt;/title&gt;
        ///		&lt;!-- googleapis : fonts --&gt;
        ///		&lt;link href=&quot;https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&amp;display=swap&quot; rel=&quot;stylesheet&quot; /&gt;
        ///		&lt;!-- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string introduction_html {
            get {
                return ResourceManager.GetString("introduction-html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;card-body&quot;&gt;
        ///	&lt;h5 class=&quot;card-title text-start&quot;&gt;
        ///		&lt;span name=&quot;invoice-label&quot;&gt;Invoice: &lt;/span&gt;
        ///		&lt;span automationid=&apos;search-uuid&apos; name=&quot;invoice&quot; class=&quot;text-light&quot;&gt;{0}&lt;/span&gt;
        ///	&lt;/h5&gt;
        ///	&lt;div class=&quot;row&quot;&gt;
        ///		&lt;h6 class=&quot;text-start&quot;&gt;
        ///			&lt;span name=&quot;invoice-date-label&quot; class=&quot;text-primary&quot;&gt;Invoice Date: &lt;/span&gt;
        ///			&lt;span name=&quot;invoice-date&quot; class=&quot;ml-2&quot;&gt;{1}&lt;/span&gt;
        ///		&lt;/h6&gt;
        ///		&lt;h6 class=&quot;text-start&quot;&gt;
        ///			&lt;span name=&quot;invoice-description-label&quot; class=&quot;text-primary&quot;&gt;Description: &lt;/span&gt;
        ///			&lt;span name [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string invoice_content_html {
            get {
                return ResourceManager.GetString("invoice-content-html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html lang=&quot;en&quot;&gt;&lt;head&gt;
        ///		&lt;script type=&quot;text/javascript&quot;&gt;
        ///                         try { 
        ///                         CefSharp.BindObjectAsync(&quot;jsHandler&quot;, &quot;jsHandler&quot;); 
        ///                              } catch { } 
        ///		&lt;/script&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, shrink-to-fit=no&quot;&gt;
        ///		&lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///		&lt;meta name=&quot;author&quot; content=&quot;&quot;&gt;
        ///		&lt;title&gt;legallead.ui: invoice generation failed&lt;/title&gt;
        ///		
        ///		&lt;!-- googleapis : fonts --&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string invoice_failure_html {
            get {
                return ResourceManager.GetString("invoice-failure-html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///	&lt;head&gt;
        ///		&lt;!-- script: common-cef-handler --&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, shrink-to-fit=no&quot;&gt;
        ///		&lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///		&lt;meta name=&quot;author&quot; content=&quot;&quot;&gt;
        ///		&lt;title&gt;legallead.ui: invoice&lt;/title&gt;
        ///		&lt;!-- block: common-headings --&gt;
        ///		&lt;!-- common styles --&gt;	
        ///		&lt;link rel=&quot;stylesheet&quot; name=&quot;base&quot; href=&quot;css/base.css&quot; /&gt;
        ///		&lt;script name=&quot;stripe-api&quot; src=&quot;https://js.stripe.com/v3/&quot;&gt;&lt;/script&gt;
        ///		&lt;style name=&quot;subcontent-css [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string invoice_html {
            get {
                return ResourceManager.GetString("invoice-html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script name=&quot;invoice-form-js&quot;&gt;
        ///
        ///let jsinvoicing = { 
        ///		close_invoice: function() {
        ///			var dv_checkout = document.getElementById(&apos;checkout&apos;);
        ///			if (undefined == dv_checkout || null == dv_checkout) {
        ///				let handler = window.jsHandler;
        ///				if( undefined === handler || null === handler || !(handler) ) { return; }
        ///				finder = &quot;span[automationid=&apos;search-uuid&apos;]&quot;;
        ///				var obj = JSON.stringify( { &quot;id&quot;: $( finder ).text() });
        ///				handler.fetch( &quot;frm-search-make-payment&quot;, obj);
        ///			}	
        ///		},
        ///		close_invo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string invoice_submission_js {
            get {
                return ResourceManager.GetString("invoice-submission-js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;script type=&quot;text/javascript&quot;&gt;
        ///        try {
        ///            CefSharp.BindObjectAsync(&quot;jsHandler&quot;, &quot;jsHandler&quot;);
        ///        } catch { }&lt;/script&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, shrink-to-fit=no&quot;&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///    &lt;meta name=&quot;author&quot; content=&quot;&quot;&gt;
        ///    &lt;title&gt;legallead.ui: mailbox&lt;/title&gt;
        ///
        ///    &lt;!-- googleapis : fonts --&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css2?family=Roboto:wght@300; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mailbox_base_html {
            get {
                return ResourceManager.GetString("mailbox-base-html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script name=&quot;mail-box-js&quot;&gt;
        ///
        ///let mailbox = {
        ///    &quot;isWorking&quot;: false,
        ///    &quot;controls&quot;: {
        ///        &quot;maillist&quot;: &quot;dv-mail-item-list&quot;,
        ///        &quot;preview&quot;: &quot;dv-mail-item-preview&quot;,
        ///        &quot;previewtemplate&quot;: &quot;tarea-preview-html&quot;,
        ///        &quot;previewcurrent&quot;: &quot;tarea-current-html&quot;
        ///    },
        ///    &quot;getElementText&quot;: function (elementName) {
        ///        try {
        ///            let js = document.getElementById(elementName).innerText.trim();
        ///            return js;
        ///        } catch {
        ///            return &quot;&quot;;
        ///        }
        ///    },
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mailbox_base_js {
            get {
                return ResourceManager.GetString("mailbox-base-js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style name=&quot;correspondence-css&quot;&gt;
        ///    html {
        ///        height: 100%;
        ///        margin: 0;
        ///    }
        ///
        ///    body {
        ///        margin-top: 10px;
        ///        background: #444;
        ///        color: white;
        ///        margin-bottom: 10px;
        ///        overflow-x: clip
        ///    }
        ///
        ///    #footer-copy {
        ///        padding-top: 10px;
        ///    }
        ///
        ///    #templates {
        ///        display: none;
        ///    }
        ///
        ///    div[name=&quot;mailbox-header&quot;] {
        ///        margin: 10px;
        ///    }
        ///
        ///    div[name=&quot;mailbox-grid&quot;] {
        ///        padding-left: 25px;
        ///    }
        ///
        ///    div[name=&quot;m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mailbox_style_css {
            get {
                return ResourceManager.GetString("mailbox-style-css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///	&lt;head&gt;
        ///		&lt;!-- script: common-cef-handler --&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, shrink-to-fit=no&quot;&gt;
        ///		&lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///		&lt;meta name=&quot;author&quot; content=&quot;&quot;&gt;
        ///		&lt;title&gt;legallead.ui: account&lt;/title&gt;
        ///		&lt;!-- block: common-headings --&gt;
        ///		&lt;!-- common styles --&gt;	
        ///		&lt;link rel=&quot;stylesheet&quot; name=&quot;base&quot; href=&quot;css/base.css&quot; /&gt;
        ///		&lt;!-- style: my-account-subcontent-css --&gt;
        ///	&lt;/head&gt;
        ///
        ///	&lt;body class=&quot;text-center&quot;&gt;
        ///	&lt;!-- componen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string myaccount_base_html {
            get {
                return ResourceManager.GetString("myaccount-base-html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style name=&quot;subcontent-css&quot;&gt;
        ///
        ///div.subcontent {
        ///	width: 50%; 
        ///	min-width: 400px;
        ///	max-width: 1200px;
        ///    margin-bottom: 20px;
        ///	display: none;
        ///}
        ///			
        ///div.subcontent.active {
        ///	display: block;
        ///}
        ///
        ///div[name=&quot;subcontent-home-bullet-list&quot;] {
        ///	width: 50%; 
        ///	margin-left: 35%;
        ///	text-align: left;
        ///	justify-content: left;
        ///}
        ///			
        ///
        ///div[name=&quot;main-content&quot;] {
        ///	width: 70%; 
        ///	min-width: 800px;
        ///	max-width: 1200px;
        ///}		
        ///
        ///div[name=&quot;subcontent-home&quot;],
        ///div[name=&quot;subcontent-profile&quot;],
        ///div[name=&quot;subconten [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string myaccount_css {
            get {
                return ResourceManager.GetString("myaccount-css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///					&lt;div id=&quot;dv-subcontent-home&quot; name=&quot;subcontent-home&quot; class=&quot;subcontent active card&quot;&gt;
        ///						&lt;div class=&quot;card-body&quot;&gt;
        ///							&lt;h5 class=&quot;card-title&quot;&gt;Account Details&lt;/h5&gt;	
        ///							&lt;div class=&quot;row&quot;&gt;
        ///								&lt;div class=&quot;col-4 text-info text-start&quot;&gt;User Name:&lt;/div&gt;
        ///								&lt;div class=&quot;col-1 text-info&quot;&gt;&lt;/div&gt;
        ///								&lt;div id=&quot;account-user-name&quot; class=&quot;col-7 text-secondary text-start&quot;&gt; - &lt;/div&gt;
        ///							&lt;/div&gt;
        ///							&lt;div class=&quot;row&quot;&gt;
        ///								&lt;div class=&quot;col-4 text-info text-start&quot;&gt;Email:&lt;/div&gt;
        ///								&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string myaccount_home_html {
            get {
                return ResourceManager.GetString("myaccount-home-html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- Logout Modal --&gt;
        ///&lt;!-- Button trigger modal --&gt;
        ///&lt;button id=&quot;btn-my-account-logout-show&quot; type=&quot;button&quot; class=&quot;btn btn-primary d-none&quot; data-bs-toggle=&quot;modal&quot; data-bs-target=&quot;#my-account-logout-modal&quot;&gt;
        ///  Launch static backdrop modal
        ///&lt;/button&gt;
        ///
        ///&lt;!-- Modal --&gt;
        ///&lt;div class=&quot;modal fade&quot; id=&quot;my-account-logout-modal&quot; data-bs-backdrop=&quot;static&quot; data-bs-keyboard=&quot;false&quot; tabindex=&quot;-1&quot; aria-labelledby=&quot;my-account-logout-label&quot; aria-hidden=&quot;true&quot;&gt;
        ///  &lt;div class=&quot;modal-dialog&quot;&gt;
        ///    &lt;div class=&quot;modal-content&quot;&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string myaccount_logout {
            get {
                return ResourceManager.GetString("myaccount-logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///					&lt;div id=&quot;dv-subcontent-password&quot; name=&quot;subcontent-password&quot; class=&quot;subcontent card&quot;&gt;
        ///                        &lt;div id=&quot;dv-subcontent-password-row-00&quot; class=&quot;row d-none w-75&quot;&gt;
        ///							&lt;div id=&quot;dv-subcontent-password-success&quot; class=&quot;alert alert-success d-flex align-items-center&quot; role=&quot;alert&quot;&gt;
        ///								&lt;div class=&quot;row&quot;&gt;
        ///                                    &lt;i class=&quot;bi bi-check-circle-fill&quot;&gt;&lt;/i&gt;
        ///								    &lt;span&gt;Your account information has been updated successfully&lt;/span&gt;
        ///								&lt;/div&gt;
        ///							&lt;/di [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string myaccount_password_html {
            get {
                return ResourceManager.GetString("myaccount-password-html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///					&lt;div id=&quot;dv-subcontent-permissions&quot; name=&quot;subcontent-permissions&quot; class=&quot;subcontent card&quot;&gt;
        ///                        &lt;div id=&quot;dv-subcontent-permissions-row-00&quot; class=&quot;row d-none w-75&quot;&gt;
        ///							&lt;div id=&quot;dv-subcontent-permissions-success&quot; class=&quot;alert alert-success d-flex align-items-center&quot; role=&quot;alert&quot;&gt;
        ///								&lt;div class=&quot;row&quot;&gt;
        ///                                    &lt;i class=&quot;bi bi-check-circle-fill&quot;&gt;&lt;/i&gt;
        ///								    &lt;span&gt;Your account information has been updated successfully&lt;/span&gt;
        ///								&lt;/div&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string myaccount_permissions_html {
            get {
                return ResourceManager.GetString("myaccount-permissions-html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to let permissions_general = {
        /// &quot;change_form&quot;: {
        ///	&quot;alertTimer&quot; : null,
        ///	&quot;button&quot;: &quot;#frm-permissions-submit-button&quot;,
        ///	&quot;icons&quot;: {
        ///		&quot;normal&quot;: &quot;#form-permissions-icon&quot;,
        ///		&quot;spin&quot;: &quot;#form-permissions-icon-spin&quot;
        ///	},
        ///	&quot;error&quot;: &quot;#frm-permissions-error-message&quot;,
        ///	&quot;setIcon&quot;: function( isSpinning ) {
        ///		const dsb = &quot;disabled&quot;;
        ///		const hddn = &quot;d-none&quot;;
        ///		let frm = permissions_general.change_form;
        ///		let icons = [ frm.icons.normal, frm.icons.spin ];
        ///		var bttn = frm.button;
        ///		let a = isSpinning ? 0 : 1;
        ///		let [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string myaccount_permissions_validation_js {
            get {
                return ResourceManager.GetString("myaccount-permissions-validation-js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///					&lt;div id=&quot;dv-subcontent-profile&quot; name=&quot;subcontent-profile&quot; class=&quot;subcontent card&quot;&gt;
        ///						&lt;div id=&quot;dv-subcontent-profile-row-00&quot; class=&quot;row d-none w-75&quot;&gt;
        ///							&lt;div id=&quot;dv-subcontent-profile-success&quot; class=&quot;alert alert-success d-flex align-items-center&quot; role=&quot;alert&quot;&gt;
        ///								&lt;div class=&quot;row&quot;&gt;
        ///                                    &lt;i class=&quot;bi bi-check-circle-fill&quot;&gt;&lt;/i&gt;
        ///								    &lt;span&gt;Your account information has been updated successfully&lt;/span&gt;
        ///								&lt;/div&gt;
        ///							&lt;/div&gt;
        ///						&lt;/div&gt;
        ///				 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string myaccount_profile_html {
            get {
                return ResourceManager.GetString("myaccount-profile-html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;
        ////* inject: permissions-validation script */
        ///let profileAlertTimer = null;
        ///let profileNames = [ &quot;frm-profile-address&quot;, &quot;frm-profile-personal&quot;, &quot;frm-profile-phone&quot;, &quot;frm-profile-email&quot; ];
        ///let profileButtonName = &quot;frm-profile-submit-button&quot;;
        ///let profileStatusDiv = &quot;frm-profile-error-message&quot;;
        ///var profileicons = {
        ///    spin: &quot;#form-profile-icon-spin&quot;,
        ///    normal: &quot;#form-profile-icon&quot;
        ///}
        ///
        ///function setSuccessAlert( isActive ) {
        ///	const hddn = &quot;d-none&quot;;
        ///	const parentDv = &quot;#dv-subcontent-profile- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string myaccount_profile_validation_js {
            get {
                return ResourceManager.GetString("myaccount-profile-validation-js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;
        ///	const actv = &quot;active&quot;;
        ///	const names = [ &quot;home&quot;, &quot;profile&quot;, &quot;permissions&quot;, &quot;password&quot; ];
        ///
        ///	function showLogout() {
        ///		let bttn = &quot;#btn-my-account-logout-show&quot;;
        ///		$( bttn ).click();
        ///		return null;
        ///	}
        ///
        ///	function setDisplay( name ) {
        ///			if (names.indexOf( name ) &lt; 0 ) { return; }
        ///			setActiveDiv(name);
        ///			const themenu = document.getElementById(&quot;masthead-nav-menu&quot;);
        ///			let thelinks = themenu.getElementsByTagName(&quot;a&quot;);
        ///
        ///			for(let i = 0; i &lt; thelinks.length; i++) {
        ///				let a = thelinks[ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string myaccount_script_js {
            get {
                return ResourceManager.GetString("myaccount-script-js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///					&lt;div id=&quot;dv-subcontent-home&quot; name=&quot;subcontent-home&quot; class=&quot;subcontent active card&quot;&gt;
        ///						&lt;div class=&quot;card-body&quot;&gt;
        ///							&lt;h5 class=&quot;card-title&quot;&gt;Account Details&lt;/h5&gt;	
        ///							&lt;div class=&quot;row&quot;&gt;
        ///								&lt;div class=&quot;col-4 text-info text-start&quot;&gt;User Name:&lt;/div&gt;
        ///								&lt;div class=&quot;col-1 text-info&quot;&gt;&lt;/div&gt;
        ///								&lt;div id=&quot;account-user-name&quot; class=&quot;col-7 text-secondary text-start&quot;&gt; - &lt;/div&gt;
        ///							&lt;/div&gt;
        ///							&lt;div class=&quot;row&quot;&gt;
        ///								&lt;div class=&quot;col-4 text-info text-start&quot;&gt;Email:&lt;/div&gt;
        ///								&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string myaccounthome_html {
            get {
                return ResourceManager.GetString("myaccounthome_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///					&lt;div id=&quot;dv-subcontent-profile&quot; name=&quot;subcontent-profile&quot; class=&quot;subcontent card&quot;&gt;
        ///						&lt;div id=&quot;dv-subcontent-profile-row-00&quot; class=&quot;row d-none w-75&quot;&gt;
        ///							&lt;div id=&quot;dv-subcontent-profile-success&quot; class=&quot;alert alert-success d-flex align-items-center&quot; role=&quot;alert&quot;&gt;
        ///								&lt;div class=&quot;row&quot;&gt;
        ///                                    &lt;i class=&quot;bi bi-check-circle-fill&quot;&gt;&lt;/i&gt;
        ///								    &lt;span&gt;Your account information has been updated successfully&lt;/span&gt;
        ///								&lt;/div&gt;
        ///							&lt;/div&gt;
        ///						&lt;/div&gt;
        ///				 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string myaccountpermissions_html {
            get {
                return ResourceManager.GetString("myaccountpermissions_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///					&lt;div id=&quot;dv-subcontent-profile&quot; name=&quot;subcontent-profile&quot; class=&quot;subcontent card&quot;&gt;
        ///						&lt;div id=&quot;dv-subcontent-profile-row-00&quot; class=&quot;row d-none w-75&quot;&gt;
        ///							&lt;div id=&quot;dv-subcontent-profile-success&quot; class=&quot;alert alert-success d-flex align-items-center&quot; role=&quot;alert&quot;&gt;
        ///								&lt;div class=&quot;row&quot;&gt;
        ///                                    &lt;i class=&quot;bi bi-check-circle-fill&quot;&gt;&lt;/i&gt;
        ///								    &lt;span&gt;Your account information has been updated successfully&lt;/span&gt;
        ///								&lt;/div&gt;
        ///							&lt;/div&gt;
        ///						&lt;/div&gt;
        ///				 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string myaccountprofile_html {
            get {
                return ResourceManager.GetString("myaccountprofile_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///	&lt;head&gt;
        ///		&lt;!-- script: common-cef-handler --&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, shrink-to-fit=no&quot;&gt;
        ///		&lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///		&lt;meta name=&quot;author&quot; content=&quot;&quot;&gt;
        ///		&lt;title&gt;legallead.ui: search&lt;/title&gt;
        ///		&lt;!-- block: common-headings --&gt;
        ///		&lt;!-- common styles --&gt;	
        ///		&lt;link rel=&quot;stylesheet&quot; name=&quot;base&quot; href=&quot;css/base.css&quot; /&gt;
        ///		&lt;!-- style: my-account-subcontent-css --&gt;
        ///		&lt;style name=&quot;mysearch-purchase-css&quot;&gt;						 
        ///			#formF [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mysearch_base_html {
            get {
                return ResourceManager.GetString("mysearch-base-html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///					&lt;div id=&quot;dv-subcontent-history&quot; name=&quot;subcontent-history&quot; class=&quot;subcontent card d-none w-75&quot;&gt;
        ///						&lt;div class=&quot;card-body&quot;&gt;
        ///							
        ///							&lt;h5 class=&quot;row d-flex justify-content-between&quot;&gt;
        ///								&lt;div class=&quot;col-9&quot;&gt;Search History&lt;/div&gt;
        ///								&lt;div class=&quot;col-2&quot;&gt;
        ///									&lt;button id=&quot;bttn-active-searches-filter&quot; 
        ///									title=&quot;Filter By Status&quot;
        ///									onclick=&quot;jssearchpager.toggle_filter()&quot;
        ///									name=&quot;search-history-filter&quot; class=&quot;btn btn-outline-primary&quot;&gt;
        ///										&lt;i class=&quot;bi bi- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mysearch_history_html {
            get {
                return ResourceManager.GetString("mysearch-history-html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- Search Preview Modal --&gt;
        ///&lt;!-- Modal --&gt;
        ///&lt;div class=&quot;modal fade&quot; id=&quot;my-search-preview-modal&quot; data-bs-backdrop=&quot;static&quot; data-bs-keyboard=&quot;false&quot; tabindex=&quot;-1&quot; aria-labelledby=&quot;my-search-preview-label&quot; aria-hidden=&quot;true&quot;&gt;
        ///  &lt;div class=&quot;modal-dialog&quot;&gt;
        ///    &lt;div class=&quot;modal-content&quot;&gt;
        ///        &lt;div class=&quot;modal-header&quot;&gt;
        ///            &lt;h1 class=&quot;modal-title fs-5 text-muted&quot; id=&quot;my-search-preview-label&quot;&gt;Preview Or Purchase&lt;/h1&gt;
        ///            &lt;button id=&quot;my-search-preview-x-close&quot; type=&quot;button&quot; class=&quot;btn-cl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mysearch_preview_html {
            get {
                return ResourceManager.GetString("mysearch-preview-html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///					&lt;div id=&quot;dv-subcontent-purchases&quot; name=&quot;subcontent-purchases&quot; class=&quot;subcontent card d-none w-75&quot;&gt;
        ///						&lt;div class=&quot;card-body&quot;&gt;
        ///							&lt;h5 class=&quot;row d-flex justify-content-between&quot;&gt;
        ///								&lt;div class=&quot;col-9&quot;&gt;Purchase History&lt;/div&gt;
        ///								&lt;div class=&quot;col-2&quot;&gt;
        ///									&lt;button id=&quot;bttn-purchases-history-filter&quot; 
        ///									title=&quot;Filter By Status&quot;
        ///									onclick=&quot;jsPurchases.toggle_filter()&quot;
        ///									name=&quot;purchases-history-filter&quot; class=&quot;btn btn-outline-primary&quot;&gt;
        ///										&lt;i class=&quot;bi bi- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mysearch_purchases_html {
            get {
                return ResourceManager.GetString("mysearch-purchases-html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script name=&quot;search-form-js&quot;&gt;
        ///
        ///let jsSearchForm = { 
        ///    attributes: { 
        ///    name: &quot;style&quot;, 
        ///    hide: &quot;display: none&quot;, 
        ///    block: &quot;display: block&quot; 
        ///    }, 
        ///	fields: [],
        ///    controls : { 
        ///    state: &quot;#cbo-search-state&quot;, 
        ///    county: &quot;#cbo-search-county&quot;, 
        ///    button: &quot;#search-submit-button&quot;, 
        ///    errormessage: &quot;#search-submit-error-message&quot;, 
        ///    rows: &quot;#table-search tr[name = &apos;tr-search-dynamic&apos;]&quot;,
        ///    start: &quot;#tbx-search-startdate&quot;, 
        ///    end: &quot;#tbx-search-enddate&quot;,
        ///    },
        ///    serialized [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mysearch_script_js {
            get {
                return ResourceManager.GetString("mysearch-script-js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;dv-subcontent-search&quot; name=&quot;subcontent-search&quot; class=&quot;card&quot;&gt;
        ///	&lt;div id=&quot;dv-subcontent-search-card-body&quot; name=&quot;subcontent-search-body&quot; class=&quot;card-body&quot;&gt;
        ///		&lt;h5 class=&quot;card-title text-start&quot;&gt;Search&lt;/h5&gt;
        ///		&lt;div class=&quot;row&quot;&gt;
        ///			&lt;div id=&quot;dv-search-table-wrapper&quot; name=&quot;search-wrapper&quot; class=&quot;table-responsive&quot;&gt;
        ///				&lt;table id=&quot;table-search&quot; name=&quot;search-table&quot; class=&quot;m-2 w-75 rounded border-secondary&quot;&gt;
        ///					&lt;colgroup&gt;
        ///						&lt;col style=&quot;width: 120px;&quot;&gt;
        ///						&lt;col&gt;
        ///					&lt;/colgroup&gt;
        ///					&lt;tfoot&gt;
        ///			 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mysearch_search_frame {
            get {
                return ResourceManager.GetString("mysearch-search-frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;dv-search-container&quot; name=&quot;search-container&quot; class=&quot;subcontent card&quot;&gt;
        ///	&lt;div class=&quot;card-body&quot;&gt;
        ///		&lt;h5 class=&quot;card-title&quot;&gt;Search&lt;/h5&gt;
        ///		&lt;p class=&quot;lead&quot;&gt;Complete the fields below to begin search&lt;/p&gt;
        ///		&lt;div id=&quot;dv-search-table-wrapper&quot; name=&quot;search-wrapper&quot; class=&quot;table-responsive&quot;&gt;
        ///			&lt;table id=&quot;table-search&quot; name=&quot;search-table&quot; class=&quot;container p-2 w-75 rounded border-secondary&quot;&gt;
        ///				&lt;colgroup&gt;
        ///				&lt;col style=&quot;width: 150px;&quot;&gt;
        ///				&lt;col&gt;
        ///				&lt;/colgroup&gt;
        ///				&lt;tbody&gt;
        ///					&lt;tr id=&quot;tr-search-sta [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mysearch_search_html {
            get {
                return ResourceManager.GetString("mysearch-search-html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style name=&quot;my-active-searches&quot;&gt;
        ///	#dv-main-content {
        ///		position: relative;
        ///	}
        ///	#cbo-my-active-searches {
        ///		width: 92%;
        ///		position: relative;
        ///		left: 15px;
        ///		background-color: #444 !important;
        ///	}
        ///	#my-active-searches-row-02-01 {
        ///		position: relative;
        ///		left: 10px;
        ///	}
        ///	#my-active-searches-row-01 div.col-5,
        ///	#my-active-searches-row-01 div.col-6,
        ///	#my-active-searches-row-02-01 {
        ///		max-height: 300px;
        ///		overflow-y: auto;
        ///		padding-bottom: 10px;
        ///	}
        ///	#my-active-searches-row-01 ul,
        ///	#my-active [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mysearchactive_css {
            get {
                return ResourceManager.GetString("mysearchactive-css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///	&lt;head&gt;
        ///		&lt;!-- script: common-cef-handler --&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, shrink-to-fit=no&quot;&gt;
        ///		&lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///		&lt;meta name=&quot;author&quot; content=&quot;&quot;&gt;
        ///		&lt;title&gt;legallead.ui: active searches&lt;/title&gt;
        ///		&lt;!-- block: common-headings --&gt;
        ///		&lt;!-- common styles --&gt;	
        ///		&lt;link rel=&quot;stylesheet&quot; name=&quot;base&quot; href=&quot;css/base.css&quot; /&gt;
        ///		&lt;!-- style: my-account-subcontent-css --&gt;
        ///		&lt;!-- style: my-active-searches-css --&gt;
        ///	&lt;/he [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mysearchactive_html {
            get {
                return ResourceManager.GetString("mysearchactive-html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script name=&quot;active-searches-js&quot;&gt;
        ///
        ///function onActiveCompleted()
        ///{
        ///	let handler = window.jsHandler;
        ///	if( undefined === handler || null === handler || !(handler) ) { return; }
        ///	handler.populate();
        ///}
        ///
        ///function injectJson(json) {
        ///	$(active_search.controls.txjson).text(json);
        ///	active_search.bind.all();
        ///}
        ///
        ///
        ///let active_search = {
        ///	&quot;controls&quot;: {
        ///		&quot;txjson&quot; : &quot;#text-my-active-searches-js&quot;,
        ///		&quot;cbo&quot; : &quot;#cbo-my-active-searches&quot;,
        ///		&quot;cbo_option&quot; : &quot;#cbo-my-active-searches option&quot;,
        ///		&quot;heading_no_data&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mysearchactive_js {
            get {
                return ResourceManager.GetString("mysearchactive-js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;&lt;head&gt;
        ///		&lt;script type=&quot;text/javascript&quot;&gt;
        ///                         try { 
        ///                         CefSharp.BindObjectAsync(&quot;jsHandler&quot;, &quot;jsHandler&quot;); 
        ///                              } catch {} 
        ///
        ///
        ///		&lt;/script&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, shrink-to-fit=no&quot;&gt;
        ///		&lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///		&lt;meta name=&quot;author&quot; content=&quot;&quot;&gt;
        ///		&lt;title&gt;legallead.ui: search&lt;/title&gt;
        ///		
        ///		&lt;!-- googleapis : fonts --&gt;
        ///		&lt;link h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mysearchtemplate_html {
            get {
                return ResourceManager.GetString("mysearchtemplate-html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///&quot;name&quot;: &quot;legallead.reader.service&quot;,
        ///&quot;folder&quot;: &quot;_ll-applications&quot;,
        ///&quot;isEnabled&quot;: true
        ///}.
        /// </summary>
        internal static string queuesetting_json {
            get {
                return ResourceManager.GetString("queuesetting-json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;table automationId=&quot;search-history-table&quot; name=&quot;search-dt-table&quot;&gt;
        ///	&lt;colgroup&gt;
        ///		&lt;col name=&quot;requested-date&quot; /&gt;
        ///		&lt;col name=&quot;state-abbr&quot; style=&quot;width: 60px&quot; /&gt;
        ///		&lt;col name=&quot;county-name&quot; style=&quot;width: 150px&quot; /&gt;
        ///		&lt;col name=&quot;begin-date&quot; style=&quot;width: 95px&quot; /&gt;
        ///		&lt;col name=&quot;ending-date&quot; style=&quot;width: 95px&quot; /&gt;
        ///		&lt;col name=&quot;search-status&quot; style=&quot;width: 90px&quot; /&gt;
        ///	&lt;/colgroup&gt;
        ///	&lt;thead&gt;
        ///		&lt;tr&gt;
        ///			&lt;th style=&quot;padding-left: 3px;&quot;&gt;Request Date&lt;/th&gt;
        ///			&lt;th style=&quot;padding-left: 3px;&quot;&gt;State&lt;/th&gt;
        ///			&lt;th style=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string searchhistory_table_html {
            get {
                return ResourceManager.GetString("searchhistory-table-html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style name=&quot;subcontent-css&quot;&gt;
        ///
        ///			div.subcontent {
        ///				width: 50%; 
        ///				min-width: 400px;
        ///				max-width: 1200px;
        ///                margin-bottom: 20px;
        ///				display: none;
        ///			}
        ///			
        ///			div.subcontent.active {
        ///				display: block;
        ///			}
        ///
        ///			div[name=&quot;subcontent-home-bullet-list&quot;] {
        ///				width: 50%; 
        ///				margin-left: 35%;
        ///				text-align: left;
        ///				justify-content: left;
        ///			}
        ///			
        ///
        ///			div[name=&quot;main-content&quot;] {
        ///				width: 70%; 
        ///				min-width: 800px;
        ///				max-width: 1200px;
        ///			}		
        ///
        ///			div[nam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string subcontent_css {
            get {
                return ResourceManager.GetString("subcontent-css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script name=&quot;verify-and-post&quot;&gt;
        ///
        ///function verifyAndPost(pagename, buttonname) { 
        ///    const domain = &quot;http://internal.legalead.com/&quot; 
        ///    const target = &quot;&quot;.concat(pagename, &quot;/&quot;, buttonname); 
        ///    const keyname = &quot;&quot;.concat(pagename, &quot;-&quot;, buttonname); 
        ///    const destination = &quot;&quot;.concat(domain, target);
        ///    const nonauthorization = [ &quot;user&quot;, &quot;home&quot; ];
        ///    if ( pagename == &apos;user&apos; &amp;&amp; buttonname == &apos;logout&apos; ) {
        ///        let handler = window.jsHandler;
        ///	    if( undefined === handler || null === handler ||  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string verifyandpost_js {
            get {
                return ResourceManager.GetString("verifyandpost-js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;script type=&quot;text/javascript&quot;&gt;
        ///        try {
        ///            CefSharp.BindObjectAsync(&quot;jsHandler&quot;, &quot;jsHandler&quot;);
        ///        } catch { }&lt;/script&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, shrink-to-fit=no&quot;&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///    &lt;meta name=&quot;author&quot; content=&quot;&quot;&gt;
        ///    &lt;title&gt;legallead.ui: search history&lt;/title&gt;
        ///
        ///    &lt;!-- googleapis : fonts --&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css2?family=Roboto:wg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string viewhistory_base_html {
            get {
                return ResourceManager.GetString("viewhistory-base-html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script name=&quot;view-history-box-js&quot;&gt;
        ///function getName(find, source) {
        ///	let kvp = source.split(&apos;,&apos;);
        ///    for (let k = 0; k &lt; kvp.length; k++) {
        ///        let collection = kvp[k].split(&apos;:&apos;);
        ///	    for(let i = 0; i &lt; collection.length; i++) {
        ///            let itm = collection[i].trim();
        ///		    if (itm == find &amp;&amp; i + 1 &lt; collection.length) {
        ///			    return collection[i+1].trim();
        ///		    }
        ///	    }
        ///    }
        ///	return &apos;&apos;;
        ///}
        ///
        ///let historypager = {
        ///    &quot;pagers&quot;: [&quot;#cbo-subcontent-history-pager&quot;],
        ///    &quot;history_row_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string viewhistory_base_js {
            get {
                return ResourceManager.GetString("viewhistory-base-js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table automationId=&quot;search-preview-table&quot; style=&quot;width: 95%&quot;&gt;
        ///				&lt;colgroup&gt;
        ///					&lt;col name=&quot;heading&quot; style=&quot;width: 115px&quot; /&gt;
        ///					&lt;col name=&quot;detail&quot; /&gt;
        ///				&lt;/colgroup&gt;
        ///				&lt;thead&gt;
        ///                    &lt;tr&gt;
        ///                        &lt;th style=&quot;padding-left: 3px;&quot; colspan=&quot;2&quot;&gt;Search Detail&lt;/th&gt;
        ///                    &lt;/tr&gt;
        ///				&lt;/thead&gt;
        ///				&lt;tbody&gt;
        ///					&lt;tr name=&quot;requested-date&quot;&gt;
        ///						&lt;th style=&quot;padding-left: 10px; padding-top: 15px&quot;&gt;Request Date&lt;/th&gt;
        ///						&lt;td style=&quot;padding-top: 15px&quot;&gt;
        ///						    &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string viewhistory_item_template_html {
            get {
                return ResourceManager.GetString("viewhistory-item-template-html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style name=&quot;view-history-css&quot;&gt;
        ///html {
        ///   height: 100%;
        ///   margin: 0;
        ///}
        ///
        ///body {
        ///   margin-top: 10px;
        ///   background: #444;
        ///   color: white;
        ///   margin-bottom: 10px;
        ///   overflow-x: clip
        ///}
        ///
        ///#footer-copy {
        ///   padding-top: 10px;
        ///}
        ///
        ///#templates {
        ///   display: none;
        ///}
        ///
        ///div[name=&quot;search-history-header&quot;] {
        ///   margin: 10px;
        ///}
        ///
        ///div[name=&quot;search-history-filter&quot;] {
        ///   margin: 20px;
        ///}
        ///
        ///div[name=&quot;search-history-filter-items&quot;] {
        ///   min-width: 200px;
        ///}
        ///
        ///div[name=&quot;search-history-grid&quot;] {
        ///   pa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string viewhistory_style_css {
            get {
                return ResourceManager.GetString("viewhistory-style-css", resourceCulture);
            }
        }
    }
}
