//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace next.processor.api.tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("next.processor.api.tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;state&quot;: &quot;tx&quot;,
        ///	&quot;county&quot;: {
        ///		&quot;name&quot;: &quot;collin&quot;,
        ///		&quot;value&quot;: 26550
        ///	},
        ///	&quot;details&quot;: [
        ///		{
        ///			&quot;name&quot;: &quot;Search Type&quot;,
        ///			&quot;text&quot;: &quot;criminal case records&quot;,
        ///			&quot;value&quot;: &quot;0&quot;
        ///		}
        ///	],
        ///	&quot;start&quot;: 1722802866628,
        ///	&quot;end&quot;: 1722889266628
        ///}.
        /// </summary>
        internal static string user_payload_sample_collin {
            get {
                return ResourceManager.GetString("user_payload_sample_collin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;state&quot;: &quot;tx&quot;,
        ///	&quot;county&quot;: {
        ///		&quot;name&quot;: &quot;denton&quot;,
        ///		&quot;value&quot;: 26730
        ///	},
        ///	&quot;details&quot;: [
        ///		{
        ///			&quot;name&quot;: &quot;Court Selection&quot;,
        ///			&quot;text&quot;: &quot;All County Courts&quot;,
        ///			&quot;value&quot;: &quot;9&quot;
        ///		},
        ///		{
        ///			&quot;name&quot;: &quot;Case Type&quot;,
        ///			&quot;text&quot;: &quot;JP And County Court: Civil, Family And Probate&quot;,
        ///			&quot;value&quot;: &quot;0&quot;
        ///		}
        ///	],
        ///	&quot;start&quot;: 1723420800000,
        ///	&quot;end&quot;: 1723507200000
        ///}.
        /// </summary>
        internal static string user_payload_sample_denton {
            get {
                return ResourceManager.GetString("user_payload_sample_denton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;state&quot;: &quot;tx&quot;,
        ///	&quot;county&quot;: {
        ///		&quot;name&quot;: &quot;harris&quot;,
        ///		&quot;value&quot;: 27130
        ///	},
        ///	&quot;details&quot;: [
        ///		{
        ///			&quot;name&quot;: &quot;Search Type&quot;,
        ///			&quot;text&quot;: &quot;All Civil Courts&quot;,
        ///			&quot;value&quot;: &quot;0&quot;
        ///		}
        ///	],
        ///	&quot;start&quot;: 1696118400000,
        ///	&quot;end&quot;: 1696636800000
        ///}.
        /// </summary>
        internal static string user_payload_sample_harris {
            get {
                return ResourceManager.GetString("user_payload_sample_harris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;state&quot;: &quot;tx&quot;,
        ///	&quot;county&quot;: {
        ///		&quot;name&quot;: &quot;tarrant&quot;,
        ///		&quot;value&quot;: 28330
        ///	},
        ///	&quot;details&quot;: [
        ///		{
        ///			&quot;name&quot;: &quot;Search Type&quot;,
        ///			&quot;text&quot;: &quot;All CCL Courts&quot;,
        ///			&quot;value&quot;: &quot;2&quot;
        ///		}
        ///	],
        ///	&quot;start&quot;: 1707696000000,
        ///	&quot;end&quot;: 1707782400000
        ///}.
        /// </summary>
        internal static string user_payload_sample_tarrant {
            get {
                return ResourceManager.GetString("user_payload_sample_tarrant", resourceCulture);
            }
        }
    }
}
