//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace next.web.tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("next.web.tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;script type=&quot;text/javascript&quot;&gt;
        ///			try {
        ///				CefSharp.BindObjectAsync(&quot;jsHandler&quot;, &quot;jsHandler&quot;);
        ///			} catch {}		
        ///		&lt;/script&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, shrink-to-fit=no&quot;&gt;
        ///		&lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///		&lt;meta name=&quot;author&quot; content=&quot;&quot;&gt;
        ///		&lt;title&gt;legallead.ui&lt;/title&gt;
        ///		&lt;!-- googleapis : fonts --&gt;
        ///		&lt;link href=&quot;https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&amp;display=swap&quot; rel=&quot;styleshe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string payment_confirmation_sample {
            get {
                return ResourceManager.GetString("payment_confirmation_sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;EmailType&quot;: &quot;Personal&quot;,
        ///        &quot;Email&quot;: &quot;{{$PersonalEmail}}&quot;
        ///    },    
        ///    {
        ///        &quot;EmailType&quot;: &quot;Business&quot;,
        ///        &quot;Email&quot;: &quot;{{$BusinessEmail}}&quot;
        ///    },    
        ///    {
        ///        &quot;EmailType&quot;: &quot;Other&quot;,
        ///        &quot;Email&quot;: &quot;{{$OtherEmail}}&quot;
        ///    }
        ///].
        /// </summary>
        internal static string request_frm_profile_email {
            get {
                return ResourceManager.GetString("request_frm_profile_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;userName&quot;: &quot;{{DefaultUserName}}&quot;,
        ///  &quot;oldPassword&quot;: &quot;{{DefaultPassword}}&quot;,
        ///  &quot;newPassword&quot;: &quot;{{DefaultPassword}}&quot;,
        ///  &quot;confirmPassword&quot;: &quot;{{DefaultPassword}}&quot;
        ///}.
        /// </summary>
        internal static string request_permissions_change_password {
            get {
                return ResourceManager.GetString("request_permissions_change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Choices&quot;: [
        ///        { &quot;StateName&quot;: &quot;TX&quot;, &quot;IsSelected&quot;: true },
        ///        { &quot;StateName&quot;: &quot;TX&quot;, &quot;CountyName&quot;: &quot;Tarrant&quot;, &quot;IsSelected&quot;: false },
        ///        { &quot;StateName&quot;: &quot;TX&quot;, &quot;CountyName&quot;: &quot;Collin&quot;, &quot;IsSelected&quot;: true },
        ///        { &quot;StateName&quot;: &quot;TX&quot;, &quot;CountyName&quot;: &quot;Denton&quot;, &quot;IsSelected&quot;: true },
        ///        { &quot;StateName&quot;: &quot;TX&quot;, &quot;CountyName&quot;: &quot;Collin&quot;, &quot;IsSelected&quot;: true }
        ///    ]
        ///}.
        /// </summary>
        internal static string request_permissions_set_discount {
            get {
                return ResourceManager.GetString("request_permissions_set_discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Level&quot;: &quot;Guest&quot;
        ///}.
        /// </summary>
        internal static string request_permissions_set_permission {
            get {
                return ResourceManager.GetString("request_permissions_set_permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;AddressType&quot;: &quot;Mailing&quot;,
        ///        &quot;Address&quot;: &quot;{{$randomStreetAddress}} {{$randomCity}}, {{$randomCountry}} {{$randomInt}}&quot;
        ///    },    
        ///    {
        ///        &quot;AddressType&quot;: &quot;Billing&quot;,
        ///        &quot;Address&quot;: &quot;{{$randomStreetAddress}} {{$randomCity}}, {{$randomCountry}} {{$randomInt}}&quot;
        ///    }
        ///].
        /// </summary>
        internal static string request_profile_edit_contact_address {
            get {
                return ResourceManager.GetString("request_profile_edit_contact_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;NameType&quot;: &quot;First&quot;,
        ///        &quot;Name&quot;: &quot;{{$randomFirstName}}&quot;
        ///    },
        ///    {
        ///        &quot;NameType&quot;: &quot;Last&quot;,
        ///        &quot;Name&quot;: &quot;{{$randomLastName}}&quot;
        ///    },    
        ///    {
        ///        &quot;NameType&quot;: &quot;Company&quot;,
        ///        &quot;Name&quot;: &quot;{{$randomCompanyName}}&quot;
        ///    }
        ///].
        /// </summary>
        internal static string request_profile_edit_contact_name {
            get {
                return ResourceManager.GetString("request_profile_edit_contact_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;PhoneType&quot;: &quot;Personal&quot;,
        ///        &quot;Phone&quot;: &quot;{{$randomPhoneNumber1}}&quot;
        ///    },
        ///    {
        ///        &quot;PhoneType&quot;: &quot;Business&quot;,
        ///        &quot;Phone&quot;: &quot;{{$randomPhoneNumber2}}&quot;
        ///    },    
        ///    {
        ///        &quot;PhoneType&quot;: &quot;Other&quot;,
        ///        &quot;Phone&quot;: &quot;{{$randomPhoneNumber3}}&quot;
        ///    }
        ///].
        /// </summary>
        internal static string request_profile_edit_contact_phone {
            get {
                return ResourceManager.GetString("request_profile_edit_contact_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;key&quot;: true,
        ///    &quot;value&quot;: &quot;{\&quot;Email\&quot;:\&quot;user@example.com\&quot;,\&quot;Name\&quot;:\&quot;Email\&quot;,\&quot;Message\&quot;:\&quot;Contact details updated successfully.\&quot;,\&quot;JsonData\&quot;:\&quot;[{\\\&quot;EmailType\\\&quot;:\\\&quot;Personal\\\&quot;,\\\&quot;Email\\\&quot;:\\\&quot;Patricia94@hotmail.com\\\&quot;},{\\\&quot;EmailType\\\&quot;:\\\&quot;Business\\\&quot;,\\\&quot;Email\\\&quot;:\\\&quot;Britney_Lemke63@yahoo.com\\\&quot;},{\\\&quot;EmailType\\\&quot;:\\\&quot;Other\\\&quot;,\\\&quot;Email\\\&quot;:\\\&quot;Eleanore_Wehner@yahoo.com\\\&quot;}]\&quot;}&quot;
        ///}.
        /// </summary>
        internal static string response_frm_profile_email {
            get {
                return ResourceManager.GetString("response_frm_profile_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test.account.
        /// </summary>
        internal static string response_permissions_change_password {
            get {
                return ResourceManager.GetString("response_permissions_change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;name&quot;: &quot;Discount&quot;,
        ///    &quot;email&quot;: &quot;user@example.com&quot;,
        ///    &quot;request&quot;: &quot;{\&quot;Choices\&quot;:[{\&quot;StateName\&quot;:\&quot;TX\&quot;,\&quot;CountyName\&quot;:\&quot;\&quot;,\&quot;IsSelected\&quot;:true},{\&quot;StateName\&quot;:\&quot;TX\&quot;,\&quot;CountyName\&quot;:\&quot;Tarrant\&quot;,\&quot;IsSelected\&quot;:false},{\&quot;StateName\&quot;:\&quot;TX\&quot;,\&quot;CountyName\&quot;:\&quot;Collin\&quot;,\&quot;IsSelected\&quot;:true},{\&quot;StateName\&quot;:\&quot;TX\&quot;,\&quot;CountyName\&quot;:\&quot;Denton\&quot;,\&quot;IsSelected\&quot;:true},{\&quot;StateName\&quot;:\&quot;TX\&quot;,\&quot;CountyName\&quot;:\&quot;Collin\&quot;,\&quot;IsSelected\&quot;:true}]}&quot;,
        ///    &quot;dto&quot;: {
        ///        &quot;id&quot;: &quot;15e9d380-59d0-11ef-99ce-0af7a01f52e9&quot;,
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string response_permissions_set_discount {
            get {
                return ResourceManager.GetString("response_permissions_set_discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;name&quot;: &quot;PermissionLevel&quot;,
        ///    &quot;email&quot;: &quot;user@example.com&quot;,
        ///    &quot;request&quot;: &quot;{\&quot;Level\&quot;:\&quot;Guest\&quot;}&quot;,
        ///    &quot;dto&quot;: {
        ///        &quot;id&quot;: &quot;30ee4c06-59d0-11ef-99ce-0af7a01f52e9&quot;,
        ///        &quot;userId&quot;: &quot;cf35094a-ad64-41dd-9f2d-32cbc942aaed&quot;,
        ///        &quot;customerId&quot;: &quot;cus_PgO7oP4YD73gx9&quot;,
        ///        &quot;externalId&quot;: &quot;hIzMImN7aqPUTWvZ&quot;,
        ///        &quot;invoiceUri&quot;: &quot;NONE&quot;,
        ///        &quot;levelName&quot;: &quot;guest&quot;,
        ///        &quot;sessionId&quot;: &quot;NONE&quot;,
        ///        &quot;isPaymentSuccess&quot;: true,
        ///        &quot;completionDate&quot;: &quot;2024-08-14T00:00:18&quot;,
        ///        &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string response_permissions_set_permission {
            get {
                return ResourceManager.GetString("response_permissions_set_permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;key&quot;: true,
        ///    &quot;value&quot;: &quot;{\&quot;Email\&quot;:\&quot;user@example.com\&quot;,\&quot;Name\&quot;:\&quot;Address\&quot;,\&quot;Message\&quot;:\&quot;Contact details updated successfully.\&quot;,\&quot;JsonData\&quot;:\&quot;[{\\\&quot;AddressType\\\&quot;:\\\&quot;Mailing\\\&quot;,\\\&quot;Address\\\&quot;:\\\&quot;82671 Rose Square Port Malachi, Seychelles 809\\\&quot;},{\\\&quot;AddressType\\\&quot;:\\\&quot;Billing\\\&quot;,\\\&quot;Address\\\&quot;:\\\&quot;721 Shanel Brooks East Kris, Sweden 720\\\&quot;}]\&quot;}&quot;
        ///}.
        /// </summary>
        internal static string response_profile_edit_contact_address {
            get {
                return ResourceManager.GetString("response_profile_edit_contact_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;key&quot;: true,
        ///    &quot;value&quot;: &quot;{\&quot;Email\&quot;:\&quot;user@example.com\&quot;,\&quot;Name\&quot;:\&quot;Name\&quot;,\&quot;Message\&quot;:\&quot;Contact details updated successfully.\&quot;,\&quot;JsonData\&quot;:\&quot;[{\\\&quot;NameType\\\&quot;:\\\&quot;First\\\&quot;,\\\&quot;Name\\\&quot;:\\\&quot;Adolphus\\\&quot;},{\\\&quot;NameType\\\&quot;:\\\&quot;Last\\\&quot;,\\\&quot;Name\\\&quot;:\\\&quot;Pacocha\\\&quot;},{\\\&quot;NameType\\\&quot;:\\\&quot;Company\\\&quot;,\\\&quot;Name\\\&quot;:\\\&quot;Dibbert, Pollich and Hartmann\\\&quot;}]\&quot;}&quot;
        ///}.
        /// </summary>
        internal static string response_profile_edit_contact_name {
            get {
                return ResourceManager.GetString("response_profile_edit_contact_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;key&quot;: true,
        ///    &quot;value&quot;: &quot;{\&quot;Email\&quot;:\&quot;user@example.com\&quot;,\&quot;Name\&quot;:\&quot;Name\&quot;,\&quot;Message\&quot;:\&quot;Contact details updated successfully.\&quot;,\&quot;JsonData\&quot;:\&quot;[{\\\&quot;NameType\\\&quot;:\\\&quot;First\\\&quot;,\\\&quot;Name\\\&quot;:\\\&quot;Adolphus\\\&quot;},{\\\&quot;NameType\\\&quot;:\\\&quot;Last\\\&quot;,\\\&quot;Name\\\&quot;:\\\&quot;Pacocha\\\&quot;},{\\\&quot;NameType\\\&quot;:\\\&quot;Company\\\&quot;,\\\&quot;Name\\\&quot;:\\\&quot;Dibbert, Pollich and Hartmann\\\&quot;}]\&quot;}&quot;
        ///}.
        /// </summary>
        internal static string response_profile_edit_contact_phone {
            get {
                return ResourceManager.GetString("response_profile_edit_contact_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, shrink-to-fit=no&quot;&gt;
        ///		&lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///		&lt;meta name=&quot;author&quot; content=&quot;&quot;&gt;
        ///		&lt;title&gt;oxford.leads.web&lt;/title&gt;
        ///		
        ///		&lt;!-- googleapis : fonts --&gt;
        ///		&lt;link href=&quot;https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&amp;amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///		
        ///		&lt;!-- bootstrap --&gt;
        ///		&lt;script src=&quot;https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js&quot;&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sample_payment_invoice {
            get {
                return ResourceManager.GetString("sample_payment_invoice", resourceCulture);
            }
        }
    }
}
