//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace next.processor.api.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("next.processor.api.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;api.permissions&quot;: {
        ///    &quot;destination&quot;: &quot;remote&quot;,
        ///    &quot;remote&quot;: &quot;http://api.legallead.co/&quot;,
        ///    &quot;local&quot;: &quot;https://localhost:44345/&quot;
        ///  },
        ///  &quot;post_address&quot;:{
        ///    &quot;initialize&quot;: &quot;api/queue/initialize&quot;,
        ///    &quot;update&quot;: &quot;api/queue/update&quot;,
        ///    &quot;fetch&quot;: &quot;api/queue/fetch&quot;,
        ///    &quot;start&quot;: &quot;api/queue/start&quot;,
        ///    &quot;status&quot;: &quot;api/queue/status&quot;,
        ///    &quot;complete&quot;: &quot;api/queue/complete&quot;,
        ///    &quot;finalize&quot;: &quot;api/queue/finalize&quot;,
        ///    &quot;save&quot;: &quot;api/queue/save&quot;
        ///  },
        ///  &quot;api.source&quot;: &quot;oxford.leads.data.services&quot;,
        ///  &quot;qu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string appsettings {
            get {
                return ResourceManager.GetString("appsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{
        ///		&quot;name&quot;: &quot;default&quot;,
        ///		&quot;setting&quot;: {
        ///			&quot;enabled&quot;: true,
        ///			&quot;delay&quot;: 30,
        ///			&quot;interval&quot;: 5
        ///		}
        ///	},
        ///	{
        ///		&quot;name&quot;: &quot;record.processor&quot;,
        ///		&quot;setting&quot;: {
        ///			&quot;enabled&quot;: false,
        ///			&quot;delay&quot;: 30,
        ///			&quot;interval&quot;: 1
        ///		}
        ///	}
        ///].
        /// </summary>
        internal static string background_settings_list {
            get {
                return ResourceManager.GetString("background_settings_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Name&quot;: &quot;Aleutians East&quot;,
        ///    &quot;Index&quot;: 10,
        ///    &quot;StateCode&quot;: &quot;AK&quot;,
        ///    &quot;ShortName&quot;: null,
        ///    &quot;IsActive&quot;: false
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Aleutians West&quot;,
        ///    &quot;Index&quot;: 20,
        ///    &quot;StateCode&quot;: &quot;AK&quot;,
        ///    &quot;ShortName&quot;: null,
        ///    &quot;IsActive&quot;: false
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Anchorage&quot;,
        ///    &quot;Index&quot;: 30,
        ///    &quot;StateCode&quot;: &quot;AK&quot;,
        ///    &quot;ShortName&quot;: null,
        ///    &quot;IsActive&quot;: false
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Bethel&quot;,
        ///    &quot;Index&quot;: 40,
        ///    &quot;StateCode&quot;: &quot;AK&quot;,
        ///    &quot;ShortName&quot;: null,
        ///    &quot;IsActive&quot;: false
        ///  }, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string county_list_json {
            get {
                return ResourceManager.GetString("county_list_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, shrink-to-fit=no&quot;&gt;
        ///		&lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///		&lt;meta name=&quot;author&quot; content=&quot;&quot;&gt;
        ///		&lt;title&gt;oxford.reader.service&lt;/title&gt;
        ///		
        ///		&lt;!-- googleapis : fonts --&gt;
        ///		&lt;link href=&quot;https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&amp;amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///		
        ///		&lt;!-- bootstrap --&gt;
        ///		&lt;script src=&quot;https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.j [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string home_layout {
            get {
                return ResourceManager.GetString("home_layout", resourceCulture);
            }
        }
    }
}
